services:
  music-importer:
    build: .
    expose:
      - "8080"
    env_file:
      - .env
    volumes:
      - music_data:/app/music
      - db_data:/app/data
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin
    expose:
      - "8096"
    volumes:
      - jellyfin_config:/config
      - music_data:/media/music:ro
      - /media:/zurg:rslave
    restart: unless-stopped

volumes:
  music_data:
  db_data:
  jellyfin_config:
